#client eureka settings
eureka:
  user:
    name: "{cipher}6c627b546202f13ffa9e3edf39974a3bfca5d615f58dcbfc23065661968b13c5"
    password: "{cipher}75efd89c7c4d79220a5b3f35e9ad692a69c820fa0b99e9c48ae9433d45ba016db808ab9dce78382235e529291f8aa0be"
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@127.0.0.1:8761/eureka/

spring:
  datasource:
    username: "{cipher}1a24755a7a55f36173900de1376a51b2b2752fad3b8bfaf6c2a3265f5ebdf2bf"
    password: "{cipher}45a693fd1e97832ecd80687d7710e70be5ee0b020310bda0a1b15c3e1599aa1f"
    url: jdbc:postgresql://127.0.0.1:5432/start_auth
    driverClassName: org.postgresql.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    showSql: false
    hibernate:
      ddlAuto: update
